In [1]:
import pandas as pd

In [2]:
s = pd.Series([6, 2, -5, 1], index=['a', 'b', 'c', 'd'])

In [3]:
s

a    6
b    2
c   -5
d    1
dtype: int64

In [4]:
data = {'Country': ['Japan', 'India',"France"], 'Capital': ['Tokyo', 'New Delhi', 'Paris'],'Population': [126476461, 1303171035, 65334344]}

In [5]:
data

{'Capital': ['Tokyo', 'New Delhi', 'Paris'],
 'Country': ['Japan', 'India', 'France'],
 'Population': [126476461, 1303171035, 65334344]}

In [6]:
df = pd.DataFrame(data,
                  columns=['Country', 'Capital', 'Population'])

In [7]:
df.head()

  Country    Capital  Population
0   Japan      Tokyo   126476461
1   India  New Delhi  1303171035
2  France      Paris    65334344